string_serializations for #13
cmungall/mixs-source pull request #17
Opened 2022-01-08 02:57 UTC by turbomam

string_serializations for #13

not patterns

2022-01-11 03:26 UTC, cmungall requested changes

2022-01-11 03:26 UTC, cmungall commented on gsctools/mixs_converter.py
> +                slot['string_serialization'] = ''
do you not want to do

```python
del slot['string_serialization']
```

2022-01-11 22:02 UTC, turbomam commented on gsctools/mixs_converter.py
> +                slot['string_serialization'] = ''
will do

2022-01-11 22:42 UTC, cmungall approved these changes
I might be inclined to be more defensive with the deletion (test if present first), but go ahead and merge

2022-01-19 15:20 UTC, turbomam commented
> I might be inclined to be more defensive with the deletion (test if present first), but go ahead and merge

thanks. created new issue.

2022-01-19 15:20 UTC, merged